"use client";

import { useState, useTransition } from "react";

export function RecommendationsEmptyState() {
  const [isPending, startTransition] = useTransition();
  const [status, setStatus] = useState<"idle" | "done" | "error">("idle");
  const [errMsg, setErrMsg] = useState<string>("");

  function handleGenerate() {
    startTransition(async () => {
      setStatus("idle");
      const res = await fetch("/api/recommendations/refresh", { method: "POST" });
      if (res.ok) {
        setStatus("done");
      } else {
        const body = await res.json().catch(() => ({}));
        setErrMsg(body.error ?? `HTTP ${res.status}`);
        setStatus("error");
      }
    });
  }

  return (
    <div className="max-w-lg mx-auto py-24 text-center">
      <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center mx-auto mb-4">
        <span className="text-3xl">🧠</span>
      </div>
      <h2 className="text-xl font-semibold text-gray-900 mb-2">No report generated yet</h2>
      <p className="text-sm text-gray-500 mb-6 leading-relaxed">
        Your recommendation report is generated by Claude once macro signals have been ingested
        and matched to your profile. Trigger a manual generation to get started.
      </p>
      <button
        onClick={handleGenerate}
        disabled={isPending || status === "done"}
        className="btn-primary"
      >
        {isPending ? "Generating…" : status === "done" ? "Generated ✓" : "Generate first report"}
      </button>
      {status === "done" && (
        <p className="text-xs text-gray-400 mt-3">
          Report ready — reload the page to view it.
        </p>
      )}
      {status === "error" && (
        <p className="text-xs text-red-500 mt-3">
          Generation failed: {errMsg}. Check that your profile is complete.
        </p>
      )}
    </div>
  );
}
