"use client";

import { useState, useTransition } from "react";

export function RecommendationsEmptyState() {
  const [isPending, startTransition] = useTransition();
  const [status, setStatus] = useState<"idle" | "done" | "error">("idle");
  const [errMsg, setErrMsg] = useState<string>("");

  function handleGenerate() {
    startTransition(async () => {
      setStatus("idle");
      const res = await fetch("/api/recommendations/refresh", { method: "POST" });
      if (res.ok) {
        setStatus("done");
      } else {
        const body = await res.json().catch(() => ({}));
        setErrMsg(body.error ?? `HTTP ${res.status}`);
        setStatus("error");
      }
    });
  }

  return (
    <div className="max-w-md mx-auto py-24 flex flex-col items-center text-center gap-6">
      <div className="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center">
        <span className="w-3 h-3 rounded-full bg-zinc-600 block" />
      </div>
      <div>
        <h2 className="text-[20px] font-semibold text-white tracking-[-0.02em] mb-2">
          No report generated yet
        </h2>
        <p className="text-[14px] text-zinc-500 leading-relaxed">
          Your recommendation report is generated by Claude once macro signals have been ingested
          and matched to your profile. Trigger a manual generation to get started.
        </p>
      </div>
      <button
        onClick={handleGenerate}
        disabled={isPending || status === "done"}
        className="btn-primary"
      >
        {isPending ? "Generating…" : status === "done" ? "Generated" : "Generate first report"}
      </button>
      {status === "done" && (
        <p className="text-[13px] text-zinc-400">
          Report ready — reload the page to view it.
        </p>
      )}
      {status === "error" && (
        <p className="text-[13px] text-red-500">
          Generation failed: {errMsg}. Check that your profile is complete.
        </p>
      )}
    </div>
  );
}
