"use client";

import { useState, useTransition } from "react";

export function RecommendationsEmptyState() {
  const [isPending, startTransition] = useTransition();
  const [queued, setQueued] = useState(false);

  function handleGenerate() {
    startTransition(async () => {
      await fetch("/api/recommendations/refresh", { method: "POST" });
      setQueued(true);
    });
  }

  return (
    <div className="max-w-lg mx-auto py-24 text-center">
      <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center mx-auto mb-4">
        <span className="text-3xl">🧠</span>
      </div>
      <h2 className="text-xl font-semibold text-gray-900 mb-2">No report generated yet</h2>
      <p className="text-sm text-gray-500 mb-6 leading-relaxed">
        Your recommendation report is generated by Claude once macro signals have been ingested
        and matched to your profile. Trigger a manual generation to get started.
      </p>
      <button
        onClick={handleGenerate}
        disabled={isPending || queued}
        className="btn-primary"
      >
        {isPending ? "Queuing…" : queued ? "Generation queued ✓" : "Generate first report"}
      </button>
      {queued && (
        <p className="text-xs text-gray-400 mt-3">
          Check back in a few minutes — reload the page when ready.
        </p>
      )}
    </div>
  );
}
